_target_: diverse_decoding.lm.reward_models.inform.InformRewardModel

name: InfORM
device_map: auto 
torch_dtype_name: torch.bfloat16 
local_model_weights_dir: /data/model-weights
s3_model_weights_dir: s3://aminra/model-weights/